language: node_js
node_js:
    - "12"
env:
    global:
        - NODE_ENV=test
script:
    - npm install
    - npm run test:unit
branches:
    only:
        - master
    except:
        - build
addons:
    apt:
        packages:
            - libgif-dev
